name: customer-service
image:
  repository: customer-service
labels:
  owner: customer-domain
  costCenter: cc-sales
  dataClassification: confidential
config:
  OTEL_SERVICE_NAME: customer-service
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
