name: pricing-service
image:
  repository: pricing-service
labels:
  owner: pricing-domain
  costCenter: cc-sales
  dataClassification: confidential
config:
  OTEL_SERVICE_NAME: pricing-service
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
