sonar.projectKey=sales-customer-service
sonar.projectName=Customer Service
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*Test*,**/*.spec.ts,**/tests/**
