{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sales-service.fullname" . }}
  labels:
    {{- include "sales-service.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ index .Values.serviceAccount.annotations "azure.workload.identity/client-id" | quote }}
    keyvaultName: {{ .Values.secretProviderClass.keyVaultName | quote }}
    tenantId: {{ .Values.secretProviderClass.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
        {{- end }}
{{- end }}
