sonar.projectKey=sales-product-catalog-service
sonar.projectName=Product Catalogue
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*Test*,**/*.spec.ts,**/tests/**
