sonar.projectKey=sales-notification-service
sonar.projectName=Notification
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*Test*,**/*.spec.ts,**/tests/**
