sonar.projectKey=sales-order-service
sonar.projectName=Order Management
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*Test*,**/*.spec.ts,**/tests/**
