apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sales-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sales-platform
  source:
    repoURL: https://github.com/joselinepraveena/Sales-App-SDLC.git
    targetRevision: main
    path: gitops/argocd/applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
