sonar.projectKey=sales-sales-analytics-service
sonar.projectName=Sales Analytics
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*Test*,**/*.spec.ts,**/tests/**
